---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

rdo_admin_users:
  dmsimard:
    name: "dmsimard"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBH7d5MTSlwAKp8ejbd0GNq0YUVXIzSunGXhFigNgl1oqrTapJIsJ6aGv3p400al5YKWua3Z/DzNftkz8VfermnsWli6SJAhcYPY7SDMTlFXKyTKLbG+k917v1QdtA2g6RqlfvfGSfYj6VwA7bNKjosrceN6GI+9HqY9nLcclQZ1xCr+wNShpfQrqlYKYBnI6JG26c8HfE/H3vSHKRsry4cscx+BDTlurMPF72zdrNGvbbV6LMxY6gbLj3xrCof1GxjU0PbXEMBdePWMxFqRb9do8+iz5noHUUTIElGIpFA2z40mdZ5w1FQYt/rYa1ehNTO25nXXhFTYgn2Y+fQb25
  jpena:
    name: "jpena"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwEtxKw9XCxQUsUsRDxOpSo8+9KpX8lOlL0q9owdAb3W2YHv5d4XSlkZ78h7hDORoGLbNFEILBWb3pOJ+uDn7u7EtpZlKYqlJh3diHYCZuUETpG5WBbUExfDLLolbDdiihJKD06Y6wu8vzaDZSxrRrMuRo1PjmzsHKtoV7qip5a+jnFqPtE+DHVh8GhZkY2Qhbji0+fv4JUSLvcrLEJUIE5XHLG0BniJsTQCu4R05rBzd2gfTet95B7LSw1dNObvIVb8dnJBCQ5IFKblOAZp3M0EKdjmNdSTjgLlorqMN1F0YMi6unrfimPyH5pzd1Rnf2Cr2gcT+M55hcueHp86Lh
  apevec:
    name: "apevec"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYmpEuiWLuUFftIu+vQQmTC8m86GkNQXeNlrY9TRZtVqMZXEgIQuf9jeHZ89nKRX1eoRXH1NGk59RDiYVqOpp1NHRj+v7JjvdB8bkTCKYqyltLANRMO0gq+YAFSV7xY4DPskBLXswxhMY/5yCP9jlnXp6tdHIMfaQpdR/DjrXFt5QwrvXBbYUXoJUh/tAozlvj2w/qu41GAFPPKJ+wzl4M46YaEO39yMSbTue/g1Vn2XNWtX5Ocx41CeNFjbW5ghSJuvFHtHLG3sxT7YTwY/TTXLaVwZu4RwQEHqs9bnS6U7OWxjOxAMPuNnn3aMO/fHFheUGmmYETTfKfLXEv54UVUCq4/uqcD1UHwoddG7lQpdUmHpEBusgBc2sj+1Ysrt5EZ29iWI55Ke6FIxESOW73ttDsbgD8QC+IX2X3dhzvzI/9lKMScyO+JhzhzG3aOO9+wqqt/89Xdq3775J3IgePiDlOzcbvjIOsfgqmuaz5hPeqPLMcVThonOgl1UarsHeppyLRqykcUB0LqgmM3CGSCQaDfHulZMGfk3WsOHmj4eqW+gt4flKbzzvrB0W8ZPyCmQumqDTwZeI7EVnuNlTVUpdLZNMEjmgidEEM5aGuweA88QexefWdWwC+H9UbyL1R95Ka4f1Ek8n1oI/321nlA7ur4hLcB/c10yvWkwlFRQ==
  amoralej:
    name: "amoralej"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzSWK0/apjniWnXflcSQE+XNFDc4bWvgWnhhXj++Woc9/O7w/TrPh+3GPh7YUaNX01DVB6YgXevGTN3qm1abrKDDhlUKfuI3HTACnrd8eZQhcoyJ/SQUspbnrbQXFDU9QEmPcvZqHXtkt0Y0ihfN04Y3ba1iYkHfysFqxMvJiwYzdOcV8JD5kULkvd5hXYRxj/rSHl1k83XwKwL6adtabhgzSrsxYhCJ0LzecGN+3l3vZvhkfzV6m8YgGFMS9UpXsLzk1rbwKr8zVnj4sTgk817kGqnyrEkbCYFfiOduDnkvTSY34bJ3+LW7dsgwOiKi9KyIFt9YqVYqnIR5xovMF1
  fboucher:
    name: "fboucher"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDi8srMdr4EUBmEK8CGjOmUlEvC4bGZnmiATC3k5NxzcWC1pbT5JGLhAyMQr52FArWPV6qTs5cw/8JjBPv42Dhz8JxzLGVavXggzPdBWPKkGBMgZUiiolsGAPlZ0OAVGiQw61amQ0l/r7dumdlqNFpUTWwcLHYtZMG/RJWKAw9s3KhsQvPcIkzaJEDuanR426O4+qAmOBPD8veTWf3Gxdg4qqGYEBEEEvChyAFg0o83R1FsQMxtuox0CP4l5T6ecKHxJ0r9nym345KtgceavBAqraNJ2EOotAlPcDl/uXq2HzdV8kfOuxMso+AQvnKcHK6/JOsPepSwfGJabso8T+eyA8QoJ/LU2esFMjNCwUK0I4J9W0Tpy/2ZvJjZNnRfvS0ToRWcim0xSaGDsR17RpFe++oI9l+r3+kZGoyHeOqcz1WsRnBCd50OmcFWfXFA4cGZr91d9B6r3ZcGmnLci4yD6ikdd9qsacs7C1Tu0kJl8Wsp094YFt944AaaFYSAWJzw4/RW+QPeGAWKKieIdj4UzYGcn1Wi2j6odRDdWqq7Ei+Gy7PPtxaRALAdVVx4tDGkTPyEz1i/bGtec3Js06GrzPIBWitdg1uJumttZY//RVunevTkDT31cn295VWw/qe4J9fv+nUKRv+Xw+Q+nDLiP+6HkxL2q3UDjQOjYEY+Mw==
  nhicher:
    name: "nhicher"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcB2dFwG8DnJ12U3i/LFN2Llp825EK8K3j+Jht0/cBXDOQY2oNZLgqmuxGC65k6c2glSqboYMTwzfmLyZtBXKHIVSAP5m24vuBV+xwchR7GLQvtdAFz4Avu19GD8lGWszKjZN0QMlKJQd1YNtxjbZUxnApGlFhyMiwVkbOG87usIajQmRnPUhuN3lfMFXcBlbmupEWwIpueRshiypRlQBcYMfHnGpafDJfJ3vD2O2RvPfJy5FMktUdlJjBR75G2JO1alwOlfOhtYp5JBM0dUYYb5XexIMceCtemLTpQpU9lVxEdBKiweMzZS0v/JAxF3UKGCd/cabhQTZuMNZcgb2p
  mhuin:
    name: "mhuin"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvgV8CDCv+p1wyShIJoT718icR6z5PuHDiHFuQSIYI246BUyWFParuaL75qfD8Dz7+AXnX+leC63mhU4nqzzzfocGxjCtvDUI9+hgcYaJyp4JbBQreGSHKcayZ7lG9Nnsy6YkpMZpx7a6/BgLMMq434osqibj59qus0L9q/oZHy2suJGUoeBT9Ohm82HPZU6Cuc4YYgG12h9A77YKRE4bd4TDTQWskxCkSyMv26U7DgNnR6fvpIGNLjdoykVL8BJPh11blpoUU5rJIp06Jpy7fqs1EsgkPiD0fuELS2KdkVO3j37Llq1YZbRJh7Ld+lp0fP9sz6xr/4V3dIMaFHgpx
  tristanc:
    name: "tristanc"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOACTrxPG0N4m3ltLzeY2MMEDvRLN5utvWD78dtfvKSMsyPfpPjlmCjMFGIWeHmrl8iOZyUnu7triCKjljvDedwTFOQ1VN/KF53/sjLqZDUPE8IC8G2V5R7jnAmKmQNSrtsauZ+yOQdV9C0hff7RI5euPGYowunKXX5OOmx6zZ0abNs5pMYAS0XwsFYf2V5op4bb+sJVJQkTYu1Ezy643FH2gRubpFTC8B2LqQjzeoBougSbwRFhFMYG/0WskH/ITPXJUlUrsqwFZRhx6uLQUoFGtnE3mMHQT0365PAZYl2RfWTrfLUEvJD2BN0I3UrsfOFH0QGsCWkKlVn3vqc1otF+6hgNzhCmGNNylfjBotXy5R8DGvItj1wsnnfgYpfL3p8lhdBz6Kbntdd6Nz0BAJ0JNf24DdrFh5MEclNS55s4OwImLaWLvTfZ32RF/OvJ/sd4z8Km+bnWtfp0NfNGs+s/Kdz7KuH8VfgrsURBVoQpipQOYDck0He0JTt2DeIuIP8f36dBzjAwBUqsrkSsWDPTzYhQKoQ8ZPRba2lNgSmzQf/VLsgdp00i3On8SmGAxf9Ib/O+/RbKFhwwN5Y71DiiOvjc6UrYNHCnl+6gpGbpvpez37Qo7OZFPI2+nBQmDfpfgodpB6wQqec0d7qB0VeZYwwLJ5c7upqjq2Nz5t1w==
  hguemar:
    name: "hguemar"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF/F7wLEX8KDYV2uSLJL0U+Q7NsmlqTSHYr69pbseUdoMNnTcCON1uufjsEnWx1fOpYyDp72l2TGzEGY/AOiBn3qAX5+kVlQ8dcG6MNwTkONycP/R0LFYYWlmA42lQst97tlKCEs9g5ByVIarPWu6HCg6idAwP3CJNNPISc2Uz4UtHFnA14Zy9YOlzwPZt42JyhZWkFX46i2bwZhR1J/lNuPc/XAVRFxnp9PBHeUTsTYTFCKO4TfM8IZsSMVunEkR7AY3XxueRNuWuHCjxkFfPvlo/qY3bPP2hMfQ2Ga2CtXc546jr/fLs4WY3KUF6p505/I5HSON0uNUaVuylyXp5
  pabelanger:
    name: "pabelanger"
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuP0CZE8AYnbm8gxecCxKeRw0wHRyryd+FKmNNsdr0d3UvfCbqNzLigrqEBZsKpofi3M4qCWNpKRyfhnjPynLTQjP1vnX9AbL9UGoiHxScfvh3skntTYMs9ezJRd0rMJJZO76FPo8bJLDlwxAQl8m/nuj3HfYiO5hYE7P+a3rhsJh4nEfBb7xh+Q5yM0PWObkkBl6IRiBYjlcsXNZHgTA5kNuihUk5bHqAw54sHh05DhpgOITpTw4LFbh4Ew2NKq49dEb2xbTuAyAr2DHNOGgIwKEZpwtKZEIGEuiLbb4DQRsfivrvyOjnK2NFjQzGyNOHfsOldWHRQwUKUs8nrxKdXvqcrfMnSVaibeYK2TRL+6jd9kc5SIhWI3XLm7HbX7uXMD7/JQrkL25Rcs6nndDCH72DJLz+ynA/T5umMbNBQ9tybL5z73IOpfShRGjQYego22CxDOy7e/5OEMHNoksbFb1S02viM9O2puS7LDqqfT9JIbbPqCrbRi/zOXo0f4EXo6xKUAmd8qlV+6f/p57/qFihzQDaRFVlFEH3k7qwsw7PYGUTwkPaThe6xyZN6D5jqxCZU3aSYu+FGb0oYo+M5IxOm0Cb4NNsvvkRPxWtwSayfFGu6+m/+/RyA3GBcAMev7AuyKN+K2vGMsLagHOx4i+5ZAcUwGzLeXAENNum3w== pabelanger@redhat.com
